.TH MERB-SLICE "1" "July 2009"
.SH NAME
merb-slice \- Start a Merb slice.
.SH SYNOPSIS
.B merb-slice
.SH DESCRIPTION
The merb-slice command starts a Merb application as a slice.
.SH SEE ALSO
.br
Documentation for Merb is maintained in RDoc via the package libmerb-ruby-doc, or available on the Merb web site, http://www.merbivore.com/
.SH AUTHOR
The upstream author of Merb is Yehuda Katz <ykatz@engineyard.com>. 
This manual page was written by Joshua Timberman <joshua@opscode.com> with help2man
for the Debian and Ubuntu projects (but may be used by others). Permission is granted
to copy, modify, merge, publish, and distribute this document under the terms of the
MIT license.
