.TH SLICE "1" "July 2009"
.SH NAME
slice \- Start a Merb slice.
.SH SYNOPSIS
.B slice
.SH DESCRIPTION
The slice command starts a Merb application as a slice.
.SH SEE ALSO
.br
Full documentation of merb is available after the Merb packages are installed.
.SH AUTHOR
Merb was written by Yehuda Katz <ykatz@engineyard.com>.
.PP
This manual page was written by Joshua Timberman <joshua@opscode.com>,
for the Debian project (and may be used by others).

