.TH fog: "1" "May 2010" "Fog" 
.SH NAME
fog: \- Run an IRB session with fog preloaded.
.SH SYNOPSIS
.B fog
.SH DESCRIPTION
.TP
fog is a command-line REPL console used to work with cloud computing resources in IRB session. It uses libfog-ruby to provide access to the APIs for various cloud computing offerings.
.TP
In order to use fog, create ~/.fog with credentials for the preferred cloud computing provider. If this file does not exist, when fog is run, it will display the required format of the options to use.
.SH AUTHOR
fog is Copyright (c) 2010 Wesley Beary and distributed under the MIT license.
.PP
Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:
.PP
The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.
.PP
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.PP
This manual page was written by Joshua Timberman <joshua@opscode.com>. Permission is granted to copy, distribute and / or modify this document under the terms of the MIT License.
