#!/bin/sh
# 

set -e

case "$1" in
  configure)
        rm -f /var/lib/gems/1.9.1/source_cache
        update-alternatives --quiet --install /usr/bin/gem gem \
            /usr/bin/gem1.9.1 170 \
	    --slave /usr/share/man/man1/gem.1.gz gem.1.gz \
	    /usr/share/man/man1/gem1.9.1.1.gz \
            --slave /etc/bash_completion.d/gem bash_completion_gem \
            /etc/bash_completion.d/gem1.9.1
       ;;
  *)
esac

#DEBHELPER#

exit 0
